apiVersion: apps/v1
kind: Deployment
metadata:
  name: applysphere-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: applysphere-db
  template:
    metadata:
      labels:
        app: applysphere-db
    spec:
      containers:
      - name: db
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: "applysphere"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "securepassword"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: applysphere-db
spec:
  ports:
  - port: 5432
  selector:
    app: applysphere-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: applysphere-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: applysphere-backend
  template:
    metadata:
      labels:
        app: applysphere-backend
    spec:
      containers:
      - name: backend
        image: tarunsingh/applysphere-backend:latest
        env:
        - name: DB_HOST
          value: "applysphere-db"
        - name: DB_PASSWORD
          value: "securepassword"
        - name: JWT_SECRET
          value: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: applysphere-secrets
              key: gemini-api-key
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: applysphere-backend
spec:
  ports:
  - port: 8080
  selector:
    app: applysphere-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: applysphere-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: applysphere-frontend
  template:
    metadata:
      labels:
        app: applysphere-frontend
    spec:
      containers:
      - name: frontend
        image: tarunsingh/applysphere-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: applysphere-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: applysphere-frontend
